// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpBEyJhu0G-hcW1MJewAIwhHml_W43tBY',
    appId: '1:353534612690:web:91cb4de64b0db1dcec890b',
    messagingSenderId: '353534612690',
    projectId: 'cashistahackathon',
    authDomain: 'cashistahackathon.firebaseapp.com',
    storageBucket: 'cashistahackathon.firebasestorage.app',
    measurementId: 'G-Z2B521MVX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIpKXSuxI-R-bk16S0ThFQa6J7SPBmx4M',
    appId: '1:353534612690:android:a8ce5982f5fb1c05ec890b',
    messagingSenderId: '353534612690',
    projectId: 'cashistahackathon',
    storageBucket: 'cashistahackathon.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpBEyJhu0G-hcW1MJewAIwhHml_W43tBY',
    appId: '1:353534612690:web:cda2a677f74722baec890b',
    messagingSenderId: '353534612690',
    projectId: 'cashistahackathon',
    authDomain: 'cashistahackathon.firebaseapp.com',
    storageBucket: 'cashistahackathon.firebasestorage.app',
    measurementId: 'G-MVVR1HJSKF',
  );
}
